# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Keep Learning
subtitle:
description:
keywords: Android, Deep Learning, Tensorflow
author: Vectoros
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.vectoros.club
root: /
# permalink: :year/:month/:day/:title/
permalink: post/:abbrlink.html
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex

permalink_defaults:

# Directory
source_dir: source
public_dir: public
psot_asset_folder: true
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

archive_generator:
  per_page: 0  
  yearly: true
  monthly: true
  daily: false
  order_by: -date
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page


# Site map
sitemap: 
    path: sitemap.xml

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Hexo-neat compress
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'

gitment:
  enable: false # 是否开启gitment评论系统
  # mint: true #
  count: true # 是否显示评论数
  lazy: false # 懒加载，设置为ture时需手动展开评论
  cleanly: true # 是否隐藏'Powered by ...'
  language: # 语言，置空则随主题的语言
  github_user: vectoros # Github用户名
  github_repo: githubpagescomment # 在Github新建一个仓库用于存放评论，这是仓库名
  client_id: ad65e236934834eb5e57 # 注册OAuth Application时生成
  client_secret: 69da8ff1986c5547d5956daf47b75b2c95dc9e4f # 注册OAuth Application时生成
  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
  redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled


gitalk:
  enable: true
  githubID: vectoros	 
  repo: githubpagescomment
  ClientID: ad65e236934834eb5e57
  ClientSecret: 69da8ff1986c5547d5956daf47b75b2c95dc9e4f
  adminUser: vectoros #指定可初始化评论账户
  distractionFreeMode: true


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/vectoros/vectoros.github.io.git
  branch: master
  name: Vectoros
  email: vectoros@outlook.com
